### ISSUE TITLE
헤더 UI 구현

### ISSUE THREAD

**Issue by chaeyun-sim** [tteokguk-please/tteokguk-frontend#4]
## 어떤 기능인가요?

메인 페이지 외 모든 페이지에서 표시될 헤더 UI 컴포넌트를 구현합니다.
(추후 디자인 확인 후 상세 작업 수행)

## 작업 상세 내용

- [ ] 공통 헤더 UI 구현

**Comment by Kim-Jaemin420** [comment]
pr 단위가 너무 커질 것 같아요! 세 개 각각 따로 이슈 생성해주시면 좋을 것 같습니다.

**Comment by chaeyun-sim** [comment]
수정했습니다.

**Comment by Kim-Jaemin420** [comment]
이슈 제목도 변경 부탁드려요!
